name: Test and Build
on:
  pull_request:
    branches: [master]
  workflow_dispatch:
  
jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ["apk --debug", "appbundle --debug"]
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: temurin
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter doctor -v

      - name: Checkout code
        uses: actions/checkout@v3
      - run: flutter pub get
      - run: flutter build ${{ matrix.target }}
