name: CI
on:
  pull_request:
    branches: [master]
  
jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master
      - run: flutter doctor -v
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Resolving Dependencies
        run: flutter pub get
      - name: Build runner
        run: dart run build_runner build --delete-conflicting-outputs
      - name: Flutter analyzer
        run: flutter analyze
      - name: Check formatting
        run: dart format -o none --set-exit-if-changed .
      - name: Build
        run: flutter build apk --debug