
name: Publish
on:
  push:
    branches: [release, 24-release-pipeline]
  workflow_dispatch:

jobs:
  android:
      name: Publish Android
      runs-on: ubuntu-latest
      steps:
        - name: Set up Java
          uses: actions/setup-java@v3
          with:
            java-version: 11
            distribution: temurin
        - name: Setup flutter
          uses: subosito/flutter-action@v2
          with:
            channel: master
        - run: flutter doctor -v
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Resolving Dependencies
          run: flutter pub get
        - name: Build runner
          run: dart run build_runner build --delete-conflicting-outputs
        - run: flutter analyze
        - name: check formatting
          run: dart format -o none --set-exit-if-changed .
        - name: Decode keystore
          env:
            ENCODED_STRING: ${{ secrets.SIGNING_STORE_BASE64 }}
          run: echo $ENCODED_STRING | base64 --decode > android/keystore.jks
        - name: Build appbundle
          run: flutter build appbundle
          env:
            SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
            SIGNING_KEY_PASSWORD:  ${{ secrets.SIGNING_KEY_PASSWORD }} 
            SIGNING_STORE_PASSWORD:  ${{ secrets.SIGNING_STORE_PASSWORD }}
            SIGNING_STORE_FILE: "../keystore.jks"
        - name: Publish to Google Play
          uses: r0adkll/upload-google-play@v1
          with:
            serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
            packageName: de.moritzhuber.betterHm
            releaseFiles: build/app/outputs/bundle/release/app-release.aab
            track: internal